import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import MetaHead from "./components/MetaHead";
import { SettingsProvider } from "./context/SettingsContext";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SettingsProvider>
          <MetaHead />
        <Header />
        {children}
        <Footer  />
        </SettingsProvider>
      </body>
    </html>
  );
}
