import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import MetaHead from "./components/MetaHead";
import { SettingsProvider } from "./context/SettingsContext";


export const metadata: Metadata = {


  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: [
      // Traditional favicon format
      { url: '/assets/images/favicon.ico', type: 'image/x-icon', sizes: 'any' },
      // Modern formats (PNG/SVG)
      { url: '/assets/images/favicon.png', type: 'image/png', sizes: '16x16' },
      { url: '/assets/images/favicon.png', type: 'image/png', sizes: '32x32' },
    ],
    apple: [
      { url: '/assets/images/favicon.png' } // Apple touch icon
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SettingsProvider>
          <MetaHead />
        <Header />
        {children}
        <Footer  />
        </SettingsProvider>
      </body>
    </html>
  );
}
